#!/usr/bin/env python3

from webbrowser import open_new_tab as launch

def main():
    # launch local host index.html
    launched = launch("http://localhost/index.html")
    
    # if launch successful return 0; return 1
    if launched:
        return 0
    else:
        return 1

if __name__=="__main__":main()