#!/usr/bin/env python3

from os import remove
from os.path import join
from os.path import exists as there
from shutil import rmtree

def main():
    print("[->] UN-INIT [<-]")
    
    # get htdocs dir
    xampp = input("-> Enter htdocs location:\n-> Example: /Applications/xampp/htdocs (macos)\n-> ")
    if xampp=="":
        xampp="/Applications/xampp/htdocs"
    
    print("[->] Delete [<-]")
    
    # delete images dir if present
    if there(join(xampp, 'images')):
        rmtree(join(xampp, 'images'))
        print(f"[->] deleted {join(xampp, 'images')}*.")
    
    # delete css dir if present
    if there(join(xampp, 'css')):
        rmtree(join(xampp, 'css'))
        print(f"[->] deleted {join(xampp, 'css')}*.")
    
    # root delete paths
    deletePaths = [
        join(xampp, 'index.html'),
        join(xampp, 'login.html'),
        join(xampp, 'signup.html'),
        join(xampp, 'signup.php'),
        join(xampp, 'login.php'),
        join(xampp, 'private.html'),
        join(xampp, 'control.php'),
        join(xampp, 'appnow.php'),
        join(xampp, 'appnow.html'),
        join(xampp, 'employment.php'),
        join(xampp, 'loan.php'),
        join(xampp, 'index_loggedin.html'),
        join(xampp, 'logout.php')
    ]
    
    # delete root files
    for file in deletePaths:
        remove(file)
        print(f"[->] deleted {file}.")
    
    print("[->] END [<-]")
    

if __name__=="__main__":main()